packageExtensions:
  '@atls-ui-generators/icons@*':
    peerDependencies:
      glob: '8.0.3'
  '@atls-ui-proto/text@*':
    dependencies:
      '@emotion/react': '*'
      react: '18.2.0'
      '@emotion/styled': '*'
  '@atls-ui-proto/theme@*':
    dependencies:
      react: '17.0.1'
  '@atls-ui-parts/layout@*':
    dependencies:
      react: '17.0.1'
  '@atls/config-jest@*':
    dependencies:
      jest: '28.0.0'
      typescript: '*'
  '@atls/webpack-proto-imports-loader@*':
    peerDependencies:
      'webpack': '5.74.0'
  swiper@*:
    dependencies:
      react: '*'

yarnPath: .yarn/releases/yarn-0.0.1-git.20230217.hash-56aa982.cjs

checksumBehavior: update
