packageExtensions:
  '@atls-ui-generators/icons@*':
    peerDependencies:
      glob: '^8.0.3'
  '@atls-ui-proto/text@*':
    dependencies:
      '@emotion/react': '*'
      react: '^17.0.1'
      '@emotion/styled': '*'
  '@atls/config-jest@*':
    dependencies:
      jest: '^29.0.0'
      typescript: '*'
  '@atls-ui-proto/theme@*':
    dependencies:
      react: '^17.0.1'

yarnPath: .yarn/releases/yarn-0.0.1-git.20230217.hash-56aa982.cjs
